analytics: {}
color:
  brandColors:
    - '#0E0D13'
    - '#FCFDF8'
    - '#4B503C'
    - '#8F7F6F'
    - '#B8B6AA'
  brandStrength: 0.084459
  lightness: 0.297297
  rhythmicContrast: 0.214527
  saturation: 0.375
cta: {}
layout_spectrum: 0.987331
name: Scott Allen Huff
opengraph: {}
purpose: []
typography_spectrum: 0.695946
