name: Scott Allen Huff
favicon: null
layout_spectrum: 0.827703
typography_spectrum: 0.357264
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E8E0D0'
    - '#600818'
    - '#B05858'
    - '#E8B038'
    - '#000000'
  brandStrength: 0.152872
  lightness: 0.378378
  saturation: 0.375
  rhythmicContrast: 0.360642
purpose: []
