name: Scott Allen Huff
favicon: null
layout_spectrum: 0.74543
typography_spectrum: 0.22497
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#127500'
    - '#b89400'
    - '#84b5f0'
    - '#a6f403'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
