analytics: {}
color:
  brandColors:
    - '#E8E0D0'
    - '#600818'
    - '#B05858'
    - '#E8B038'
    - '#000000'
  brandStrength: 0.172297
  lightness: 0.5
  rhythmicContrast: 0.161318
  saturation: 0.251689
cta: {}
layout_spectrum: 0.827703
name: Scott Allen Huff
opengraph: {}
purpose: []
typography_spectrum: 0.357264
