analytics: {}
color:
  brandColors:
    - '#E8E0D0'
    - '#600818'
    - '#B05858'
    - '#E8B038'
    - '#000000'
  brandStrength: 0.152872
  lightness: 0.378378
  rhythmicContrast: 0.360642
  saturation: 0.222128
cta: {}
layout_spectrum: 0.827703
name: Scott Allen Huff
opengraph: {}
purpose: []
typography_spectrum: 0.357264
