analytics: {}
color:
  brandColors:
    - '#E8E0D0'
    - '#600818'
    - '#B05858'
    - '#E8B038'
    - '#000000'
  brandStrength: 0.252534
  lightness: 0.5
  rhythmicContrast: 0.203547
  saturation: 0.46875
cta: {}
layout_spectrum: 0.74543
name: Scott Allen Huff
opengraph: {}
purpose: []
typography_spectrum: 0.22497
